// Generated by CoffeeScript 1.9.0
(function() {
  var Enogu, bgColors, bgLightColors, colors, lightColors, up;

  Enogu = {};

  up = function(str) {
    return "" + (str.slice(0, 1).toUpperCase()) + (str.slice(1));
  };

  colors = {
    black: 30,
    red: 31,
    green: 32,
    yellow: 33,
    blue: 34,
    magenta: 35,
    cyan: 36,
    gray: 37,
    darkGray: 90,
    white: 97
  };

  bgColors = Object.keys(colors).reduce(function(o, key) {
    o[key] = colors[key] + 10;
    return o;
  }, {});

  lightColors = {
    red: 91,
    green: 92,
    yellow: 93,
    blue: 94,
    magenta: 95,
    cyan: 96
  };

  bgLightColors = Object.keys(lightColors).reduce(function(o, key) {
    o[key] = lightColors[key] + 10;
    return o;
  }, {});

  Object.keys(colors).forEach(function(key) {
    var c;
    c = colors[key];
    return Enogu[key] = function(str) {
      return "\x1b[" + c + "m" + str + "\x1b[39m";
    };
  });

  Object.keys(bgColors).forEach(function(key) {
    var c;
    c = bgColors[key];
    return Enogu["bg" + (up(key))] = function(str) {
      return "\x1b[" + c + "m" + str + "\x1b[49m";
    };
  });

  Object.keys(lightColors).forEach(function(key) {
    var c;
    c = lightColors[key];
    return Enogu["light" + (up(key))] = function(str) {
      return "\x1b[" + c + "m" + str + "\x1b[39m";
    };
  });

  Object.keys(bgLightColors).forEach(function(key) {
    var c;
    c = bgLightColors[key];
    return Enogu["bgLight" + (up(key))] = function(str) {
      return "\x1b[" + c + "m" + str + "\x1b[49m";
    };
  });

  Enogu.c256 = function(n) {
    return function(str) {
      return "\x1b[38;5;" + n + "m" + str + "\x1b[39m";
    };
  };

  Enogu.bg256 = function(n) {
    return function(str) {
      return "\x1b[48;5;" + n + "m" + str + "\x1b[49m";
    };
  };

  Enogu.closeFg = "\x1b[39m";

  Enogu.closeBg = "\x1b[49m";

  Enogu.resetg = "\x1b[0m";

  module.exports = Enogu;

}).call(this);
